# The theme of the site
theme = "zola-academic"


# The title of the site
title = "An Academic Exercise"

# The URL the site will be built for
base_url = "/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[extra]
# Put all your custom variables here

# Author of the page
author = "Emma Tosch"

# Role of the author
role = "Assistant Professor, Computer Science"

# Organizations of the author
organizations = [ 
  { name = "University of Vermont", link = "https://uvm.edu" }, 
  { name = "Center for Computer Security and Privacy", link = "https://compsec.w3.uvm.edu" } 
]

# Whether the navbar should be screen wide or page wide
wide_navbar = false

# Url of your profile pic
# You should put your portrait in the static directory.
portrait = "img/portrait.jpg"

# The links you want to put on the left of the navbar
menu_right = [
  { name = "Musings", link = "musings" },
  { name = "Research Blog", link = "posts" } 
]

menu_left = [
    { name = "Publications", link = "/#publications" },
    { name = "Projects", link = "/#projects" },
    { name = "Courses", link = "/#courses" },
    { name = "Calendar", link = "/#calendar" }
    
]

# Social icons that will appear under your profile box
social_icons = [
{icon="fa-envelope", icon_pack="fa", link="mailto:etosch@uvm.edu"},
# {icon="ai-google-scholar", icon_pack="ai", link="https://scholar.google.com/citations?user=v5dHW4wAAAAJ&hl=en"},
{icon="fa-github", icon_pack="fab", link="https://github.com/etosch" },
{icon="ai-cv", icon_pack="ai", link="cv.pdf"},
{icon = "fa-twitter", icon_pack = "fab", link = "https://twitter.com/ToschEmma"},
]

# Your interests
interests = [
    { label = "Domain-Specific Languages" },
    { label = "Methodology" }, 
    { label = "Reproducibility" }
]

# Your diplomas
education = [
{course = "PhD in Computer Science", institution = "University of Massachusetts Amherst", year = 2020},
{course = "Post-bac/MA in Computer Science", institution = "Brandeis University", year = 2011},
{course = "BA in English Literature", institution = "Wellesley College", year = 2008}
]

courses = [
  { name = "Artificial Intelligence",         institution = "UVM",           term = "Spring 2022", link="https://uvm-maple.github.io/CS295A-S22/"},
  { name = "Systems for Knowledge Discovery", institution = "UVM",           term = "Fall 2021", link="https://uvm.edu/~etosch/CS295B-F21" },
  { name = "Reinforcement Learning",          institution = "UVM",           term = "Spring 2021", link="Syllabus_CS253.pdf" },
  { name = "Reasoning Under Uncertainty",     institution = "UMass Amherst", term = "Spring 2018" },
]

# The ways people can contact you
contact_links = [
  {icon="fa-envelope", icon_pack="fa", name = "Email me", link="mailto:etosch@uvm.edu"},
  {icon = "fa-twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/ToschEmma"},
]

fun_facts = [
  { text = "I used to dabble in creative writing and have an IMDB page.", link = "https://www.imdb.com/name/nm4507616/" },
  { text = "I also used to be really into literary criticism.", link = "https://www.bu.edu/backbay/archive/1.pdf"},
  { text = "I was homeschooled (specifically, unschooled) for five years."},
  { text = "I consider my greatest accomplishments to be: (1) learning to play Maurice Ravel's Jeux D'eau and (2) teaching myself to play some of Bach's Inventions on guitar. At present, I can do none of these things."},
  { text = "I've held a variety of jobs, including clerk at a Wawa, clerk at an ACMoore, a farmhand, bank teller (very briefly!), and assistant to a mortgage broker, and many others." },
  { text = "My family is upwardly mobile and directly benefitted from LBJ's War on Poverty; many in my family are civil servants, especially K-12 teachers."},
  { text = "I delayed the start of my academic appointment to do civil service (mostly: volunteer with Arizona Voter Protection) and local election support."},
  { text = "Today my hobbies include rock climbing, cycling, and watching T.V. I'm only really good at watching T.V."}
]

# Disable the footer
disable_footer = false

# Widgets to show on main page
show_publications = true
show_posts        = false
show_projects     = true
show_courses      = true
show_contact      = false

# Choose your colorscheme among those
colorscheme = "default"
# colorscheme = "ocean"
# colorscheme = "forest"

