authors:
  etosch:
    name: Emma Tosch
    description: Research Scientist
    avatar: https://openclipart.org/image/800px/303809
  paperprice323:
    name: Zixuan Jason Yu
    description: Coop Student Researcher
    avatar: https://openclipart.org/image/800px/246278